name: Routerset
description: A Flutter application for managing router settings.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  network_info_plus: ^5.0.3
  connectivity_plus: ^6.0.5
  flutter_animate: ^4.5.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3 # Untuk menyimpan riwayat IP dan pengaturan tema
  flutter_spinkit: ^5.2.1 # Untuk animasi "verifikasi"
  system_theme: ^3.0.0 # Untuk mendeteksi tema perangkat
  url_launcher: ^6.3.1 # Untuk membuka pengaturan WiFi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tplink.png
    - assets/d-link.png
    - assets/tenda.png
    - assets/fiberhome.png
    - assets/huawei.png
    - assets/zte.png
    - assets/indihome.png